name: Clean untagged images
on:
  workflow_dispatch:

jobs:
  clean_untagged_images:
    name: Clean untagged images
    runs-on: ubuntu-22.04
    steps:
      - name: Clean untagged images
        uses: retech-us/clean-ghcr-action@v4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: someq
          repository: test-package-clean-action
          untagged_only: true
          owner_type: user
